### ISSUE TITLE
Bluemix example needs to be updated for 0.2.0

### ISSUE THREAD

**Issue by ijsnellf** [amalgam8/examples#29]
Environment variables need to be updated and it needs to use the newer versions of the images.

**Comment by zcahana** [comment]
@ijsnellf What environment variables have changed? Can I use any of the other examples (docker/k8s/etc) as a reference?

**Comment by ijsnellf** [comment]
The other examples should be up to date and usable as a reference. We added the prefix `A8_` to the environment variables for 0.2.0 to prevent environment variable conflicts. The environment variables should all be documented here:

https://github.com/amalgam8/controller/blob/master/README.md
https://github.com/amalgam8/sidecar/blob/master/README.md

**Comment by zcahana** [comment]
Already fixed in 6ffd3c4a30a47687e0495b1a415ef81778794660.
