### ISSUE TITLE
Shell script run-controlplane-docker.sh file is in DOS format

### ISSUE THREAD

**Issue by clydei** [amalgam8/examples#40]
The run-controlplane-docker.sh script returns an error when invoked in the vagrant ssh because the file is in DOS format with the Ctrl-M line terminator. The first line #!/bin/bash^M is not interpreted properly in the linux shell. When I converted the file into unix format, the script ran without any issues.

**Comment by rshriram** [comment]
Hi,
 It seems this issue is being caused by the native git client in windows converting text files to end with ^M. When this file is opened in Linux in vagrant, the shell script fails to run.
