### ISSUE TITLE
a8ctl has no action-list or action-add

### ISSUE THREAD

**Issue by rmey** [amalgam8/examples#43]
Hello I could not start the command from the tutorial:

a8ctl action-add --source reviews:v2 --destination ratings --cookie user=jason --action 'v1(1->delay=7)' does not work .
a8ctl: error: argument subcommand: invalid choice: 'action-add' (choose from 'service-list', 'route-list', 'route-set', 'route-delete', 'rule-list', 'rule-set', 'rule-clear', 'rule-delete', 'recipe-run', 'traffic-start', 'traffic-step', 'traffic-abort')

**Comment by rmey** [comment]
I changed it to a8ctl rule-set --source reviews:v2 --destination ratings --header user=jason --delay 7.0 --delay-probability 1
but I can't see a delay
user@bluemix:~/git/examples$ a8ctl route-list
+-------------+-----------------+-------------------+
| Service     | Default Version | Version Selectors |
+-------------+-----------------+-------------------+
| productpage | v1              |                   |
| ratings     | v1              |                   |
| details     | v1              |                   |
| reviews     | v1              | v2(user="jason")  |
+-------------+-----------------+-------------------+
user@bluemix:~/git/examples$ a8ctl rule-list
+------------+-------------+------------+----------------+-------------------+-------+-------------------+------------+--------------------------------------+
| Source     | Destination | Header     | Header Pattern | Delay Probability | Delay | Abort Probability | Abort Code | Rule Id                              |
+------------+-------------+------------+----------------+-------------------+-------+-------------------+------------+--------------------------------------+
| reviews:v2 | ratings     | user=jason | .*             | 1                 | 7     | 0                 | 0          | 75e324a9-5ba2-4219-a892-6ee63a0a944c |
+------------+-------------+------------+----------------+-------------------+-------+-------------------+------------+--------------------------------------+

**Comment by zcahana** [comment]
@rmey you might have hit a version incompatibility between the example docs, a8ctl, and the control plane. I believe you we're using a8ctl v0.2 (check with `pip show a8ctl`), docs's `master` branch (and later switched to `v0.2`). What version of the control plane have you deployed?

**Comment by zcahana** [comment]
By the way, we are in the process of merging the various a8 repo's under a single unidified repo, https://github.com/amalgam8/amalgam8. This should help in keeping the examples and instructions in sync with the project as it evolves.

**Comment by rshriram** [comment]
@rmey I have fixed the links to point to the right version now. If you wish, you can continue using the current version. With regard to the rule-set command, there is an error in the way you specify the command. The right command is
`a8ctl rule-set --source reviews:v2 --destination ratings:v1 --header Cookie --pattern 'user=jason' --delay-probability 1.0 --delay 7`

The bookinfo example README shows the right command.
