### ISSUE TITLE
Google instructions refer to a section that does not exist

### ISSUE THREAD

**Issue by charshy** [amalgam8/examples#5]
"7. You can now deploy the sample apps as described in "Running the sample apps" section above. Remember to replace the IP address localhost with the public IP address of the node where the gateway service is running on the Google Cloud Platform."

I'm guessing this is a holdover from an edit from the previous version - there isn't a "Running the sample apps" section (except that I created one in my latest pull request). Does this refer to the individual sample application readmes? Or is this a work-in-progress?

**Comment by rshriram** [comment]
fixed.
