### ISSUE TITLE
 examples/fluentd-logserver/README.md - readability

### ISSUE THREAD

**Issue by charshy** [amalgam8/examples#8]
examples/fluentd-logserver/README.md

I couldn't understand what the readme was trying to tell me to make any edits for clarity. Suggest that a team member edits this to make clear what it is for. If it isn't really required, we should remove it.

- Charshy.

**Comment by charshy** [comment]
Here's my brave stab-in-the-dark at fixing this readme. I've pasted it here rather than a pull request, as I suspect there will be a lot of editing required by a developer, to fix the salient technical aspects.
=====

The *fluentd-logserver* files are currently experimental. [http://www.fluentd.org/architecture](Fluentd) is an open source logging collector. 
You can use it with Amalgam8 to manage logging in your microservices architecture.

[Anything else useful about what it does here]

To enable FluentD for Amalgam8, run the following Docker commands:

  ```
  docker build -t logstore_fluentd

  docker-compose -f compose-fluentd-es.yml up -d
  ```
  
  These commands create a Fluentd container that route its logs to elasticsearch. All docker logs in your system are routed to a Fluentd container, whether you run Kubernetes or not.

  * Only logs from docker's stdout and stderr will go to Fluentd.
  * You do not need to start docker with any --log-driver option. This container mounts the /var/lib/docker/containers folder.

If you are not using FluentD, the current approach is to embed the filebeat agent in your container and configure it to forward logs to a logstash container,
which in turn can forward logs to elasticsearch. This way, you can run the entire setup locally. For Bluemix, you might want to change the logstash container to
the container supplied by Opvis (mtlogstash), which handles forwarding logs to elasticsearch. However, this has not been tested with Amalgam8.

**Comment by rshriram** [comment]
Thanks. I actually ended up removing the entire fluentd stuff. it seemed out of context as you pointed out.
